### ISSUE TITLE
Configuration type error

### ISSUE THREAD

**Issue by EmileSpecs** [TheSinding/authentication-api-key#8]
Hi @TheSinding 

I get this error when trying to use this auth strategy:
```
node_modules/@thesinding/authentication-api-key/lib/strategy.d.ts:9:14 - error TS2610: 'configuration' is defined as an accessor in class 'AuthenticationBaseStrategy', but is overridden here in 'ApiKeyStrategy' as an instance property.

9     readonly configuration: any;
```

Noob at TS so not sure how to fix this, could you take a look?

**Comment by ucokfm** [comment]
my quick fix is change this line in node_modules/@thesinding/authentication-api-key/lib/strategy.d.ts :
readonly configuration: any;
to
get configuration(): any;

and use tool like https://github.com/ds300/patch-package to preserve the changes

**Comment by TheSinding** [comment]
Sorry, I had a lot of work.

Yeah I can take a look at this issue next week

**Comment by miguelrk** [comment]
Hey @TheSinding !

I'm having the same error. Is it possible to release with the quick fix mentioned above?

So:
 ```javascript
 // changing:
 readonly configuration: any;
// to this:
get configuration(): any;
 ````
 
This is required by the Heroku setup I have for example, since I cannot change installed npm package like in local development. 

I figured I could open a PR but you might have something else in mind. Thanks!

**Comment by TheSinding** [comment]
It would be nice if you could open the PR, I have a lot on my plate atm unfortunately

**Comment by TheSinding** [comment]
So I'm looking at it now, and it looks like a TS error, the "uncompiled" code is a `get configuration()` and **not** a `readonly`

**Comment by TheSinding** [comment]
This should be fixed now, let me know!

**Comment by miguelrk** [comment]
@TheSinding woah that was fast! Thanks, just tested it and it did fix it. Really appreciate it!

**Comment by TheSinding** [comment]
No problem mate :)
